name: restaurant-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pandas=2.0.3
  - numpy=1.24.3
  - pip:
    - streamlit==1.32.0
    - cohere==4.36
    - openai==1.8.0
    - python-dotenv==1.0.0
    - joblib==1.3.2
    - matplotlib==3.7.2
description: "Environment for the Restaurant Dashboard application"
